spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mini_payment
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create  # Automatically creates/drops schema for tests
    show-sql: true